ci: corrected pre-push scripts

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -6,8 +6,11 @@
 # PULL CHANGES FROM MAIN: Ensure the branch is up to date with main
 BRANCH_NAME=$(git symbolic-ref --short HEAD)
 if [ "$BRANCH_NAME" != "main" ]; then
-  if ! git diff --quiet origin/main..HEAD; then
-    echo "ERROR: Your branch is not up to date with origin/main. Please pull the latest changes from main before pushing."
-    exit 1
+  # Check if origin/main exists before comparing
+  if git show-ref --quiet --verify refs/remotes/origin/main; then
+    if ! git diff --quiet origin/main..HEAD; then
+      echo "ERROR: Your branch is not up to date with origin/main. Please pull the latest changes from main before pushing."
+      exit 1
+    fi
   fi
 fi
